---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.3.0"
    hooks:
      - id: "check-json"
      - id: "check-merge-conflict"
      - id: "check-yaml"
        args: ["--unsafe"]
      - id: "detect-private-key"
      - id: "no-commit-to-branch"
      - id: "requirements-txt-fixer"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "mixed-line-ending"